This is required with the latest snapshot.
Without this, s4tf form the command line produces:

```
s4tf$ swift run
dyld: Symbol not found: _$s11AllKeyPathss0B12PathIterablePTl
  Referenced from: /Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2020-02-04-a.xctoolchain/usr/lib/swift/macosx/libswiftTensorFlow.dylib
  Expected in: /usr/lib/swift/libswiftCore.dylib
 in /Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2020-02-04-a.xctoolchain/usr/lib/swift/macosx/libswiftTensorFlow.dylib
Abort trap: 6
```